# Name of the database/system to use
log_database: Logging

build:
  # If True, the system will periodically rebuild the models using student data.
  rebuild_models: True
  # The minimum number of correct submisssions needed to provide feedback
  min_correct_count_for_feedback: 1
  # The database will be rebuilt each time it has this many more correct submissions
  increment: 5

conditions:
  # Options:
  # all_intervention: All students receive the intervention
  # all_control: No students receive the intervention
  # random_student: Students are assigned to a random condition when first encountered
  assignment: all_intervention
  # The probability a student is assigned to the intervention condition (0-1)
  # if assignment is set to a random setting
  intervention_probability: 0.5
  # List problems where conditions should be reversed
  inverse_problems: []
  # A map of problems where manual assignment should override the
  # primary assignment strategy. Values include "control" and "intervention".
  # NOTE: If your problem IDs are number, put them in quotes: ProblemID must be a string
  manually_assigned_problems:
    probID1: control
    probID2: intervention
