
# Name of the database/system to use
system_id: TestSystem

build:
  # The minimum number of correct submisssions needed to provide feedback
  min_correct_count_for_feedback: 10
  # The database will be rebuilt each time it has this many more correct submissions
  build_increment: 5

conditions:
  # Options:
  # all_intervention: All students receive the intervention
  # all_control: No students receive the intervention
  # random_student: Students are assigned to a random condition when first encountered
  assignment: all_intervention
  # The probability a student is assigned to the intervention condition (0-1)
  # if assignment is set to a random setting
  intervention_probability: 0.5
