
# Name of the database/system to use
log_database: Logging

# Indicates whether or not to show subgoals when available
show_subgoals: True
show_status: False

help_url: https://docs.google.com/document/d/1PpMrbRDUHrdWL8PgqQsWY6ck7KpdNUUpeCs3FvPzMxs/edit

build:
  # If provided, the models will be loaded from this database and they
  # will *NOT* be built automatically from data (ignoring below parameters)
  # The system will search for server/data/<model_database>.db.
  # Note: you can use null or ~ to indicate no database
  model_database: PCRS
  # The minimum number of correct submisssions needed to provide feedback
  min_correct_count_for_feedback: 10
  # The database will be rebuilt each time it has this many more correct submissions
  increment: 5

conditions:
  # Options:
  # all_intervention: All students receive the intervention
  # all_control: No students receive the intervention
  # random_student: Students are assigned to a random condition when first encountered
  assignment: random_student
  # The probability a student is assigned to the intervention condition (0-1)
  # if assignment is set to a random setting
  intervention_probability: 0.5
